### PR TITLE
allow language to be specified when executing a script

### PR DESCRIPTION
**Pull request by corbinbs**
Hello,

We recently released https://github.com/pokitdok/gremlin-python
and we'd like to use rexpro to easily submit python scripts to rexster for execution.
(https://github.com/pokitdok/gremlin-python#rexster)
It looks like everything is in place to do this now and we just needed to allow the `language` parameter to be passed in when running `execute`

I ran the tests locally and all of the current tests still passed:
```
corbinbs@~/Projects/github/rexpro-python (venv) [master] $ nosetests
............................................................
----------------------------------------------------------------------
Ran 60 tests in 6.863s

OK
```

please consider adding this so folks that drop gremlin-python into their rexster server can easily execute python scripts with rexpro.

Thanks for the great rexpro python library!

Brian

### CODE REVIEW

**Comment by platinummonkey** [comment]
This is Great! I was just reading about pokitdok/gremlin-python on the mailing list! Think you could add some example documentation on using it as a general approach? gremlin-python could be the prime example.

**Comment by corbinbs** [comment]
happy to add some documentation!

where's the best spot for me to include it along with this pull request? 
In the readme or somewhere in the docs folder?

**Comment by platinummonkey** [comment]
Somewhere in the docs folder, maybe create a new "examples" directory like I've done with mogwai?

**Comment by corbinbs** [comment]
Sounds good - I'll give that a shot later this afternoon and post for your review

**Comment by corbinbs** [comment]
I took a shot at dropping in some examples to illustrate some of the basics
There are a lot of other scenarios that could be included in the examples that are part of the gremlin-python test cases, but I've not had a chance to add all of them in here yet.  

Is this close to what you were thinking for building out an examples directory?

**Comment by platinummonkey** [comment]
Looks great! Thanks! I'll cut a release soon and post to PyPI

**Comment by corbinbs** [comment]
thank you!

**Pull request merged**
